repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0  # Use the version you need
    hooks:
    - id: black

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1  # Use the version you need
    hooks:
    - id: isort