"""Golden data for eager mode kernel generator tests.

Hardcoded expected values for the 256x128 causal attention kernel
generated by the eager tracer and kernel generator.

Design doc reference: nkigym_ir_guide.md section 3.
"""

TRACE_NUM_OPS_1 = 11

TRACE_OP_NAMES_1 = [
    "nc_transpose",
    "nc_transpose",
    "nc_matmul",
    "affine_select",
    "tensor_scalar",
    "tensor_reduce",
    "activation_reduce",
    "activation",
    "nc_transpose",
    "nc_matmul",
    "tensor_scalar",
]

TRACE_DIM_IDS_1 = {"d0", "d1", "d2", "d5"}

TRACE_DIM_TOTAL_SIZES_1 = {"d0": 256, "d1": 128, "d2": 256, "d5": 128}

TRACE_DIM_TILE_SIZES_1 = {"d0": 128, "d1": 128, "d2": 256, "d5": 128}

TRACE_DIM_NUM_BLOCKS_1 = {"d0": 2, "d1": 1, "d2": 1, "d5": 1}

KERNEL_CONTAINS_1 = [
    "@nki.jit",
    "def attention_kernel(Q: Tensor, K: Tensor, V: Tensor, scale):",
    "nisa.nc_transpose",
    "nisa.nc_matmul",
    "nisa.affine_select",
    "nisa.tensor_scalar",
    "nisa.tensor_reduce",
    "nisa.activation_reduce",
    "nisa.activation",
    "nisa.dma_copy",
    "nisa.tensor_copy",
    "nl.affine_range",
    "buffer=nl.sbuf",
    "buffer=nl.psum",
    "buffer=nl.shared_hbm",
]

"""
Expected 6D tensor shapes in the kernel output.
Convention: (ts_par, nb_all..., tpb_all..., ts_free...).
"""
KERNEL_SHAPE_Q_T_1 = "(128, 1, 2, 1, 1, 128)"
KERNEL_SHAPE_K_T_1 = "(128, 1, 1, 1, 1, 256)"
KERNEL_SHAPE_S_1 = "(128, 2, 1, 1, 1, 256)"
KERNEL_SHAPE_PSUM_S_1 = "(128, 1, 1, 1, 1, 256)"
KERNEL_SHAPE_DMA_Q_1 = "(128, 1, 1, 1, 1, 128)"
KERNEL_SHAPE_DMA_V_1 = "(128, 2, 1, 1, 1, 128)"

"""Expected dimension comment in docstring."""
KERNEL_DIM_COMMENT_1 = "d0: 128x2 d1: 128x1 d2: 256x1 d5: 128x1"
