"""Golden data for matmul eager mode kernel generator tests.

Hardcoded expected values for the 2048x2048 matmul kernel
generated by the eager tracer and kernel generator.

Design doc reference: nkigym_ir_guide.md section 2.
"""

TRACE_NUM_OPS_1 = 1

TRACE_OP_NAMES_1 = ["nc_matmul"]

TRACE_DIM_IDS_1 = {"d0", "d1", "d3"}

TRACE_DIM_TOTAL_SIZES_1 = {"d0": 2048, "d1": 2048, "d3": 2048}

TRACE_DIM_TILE_SIZES_1 = {"d0": 128, "d1": 128, "d3": 512}

TRACE_DIM_NUM_BLOCKS_1 = {"d0": 16, "d1": 16, "d3": 4}

KERNEL_CONTAINS_1 = [
    "@nki.jit",
    "def matmul_kernel(a: Tensor, b: Tensor):",
    "assert a.shape == (2048, 2048)",
    "assert b.shape == (2048, 2048)",
    "nisa.nc_matmul",
    "nisa.dma_copy",
    "nisa.tensor_copy",
    "nl.affine_range",
    "buffer=nl.sbuf",
    "buffer=nl.psum",
    "buffer=nl.shared_hbm",
]

"""
Expected 6D tensor shapes in the kernel output.
Convention: (ts_par, nb_all..., tpb_all..., ts_free...).
"""
KERNEL_SHAPE_SBUF_OUTPUT_1 = "(128, 16, 4, 1, 1, 512)"
KERNEL_SHAPE_PSUM_OUTPUT_1 = "(128, 1, 1, 1, 1, 512)"
KERNEL_SHAPE_DMA_A_1 = "(128, 1, 1, 1, 1, 128)"
KERNEL_SHAPE_DMA_B_1 = "(128, 1, 1, 1, 1, 512)"

"""Expected dimension comment in docstring."""
KERNEL_DIM_COMMENT_1 = "d0: 128x16 d1: 128x16 d3: 512x4"

"""Expected loop structure fragments."""
KERNEL_OUTPUT_LOOP_D1_1 = "for i_block_d1 in nl.affine_range(16):"
KERNEL_OUTPUT_LOOP_D3_1 = "for i_block_d3 in nl.affine_range(4):"
KERNEL_REDUCTION_LOOP_D0_1 = "for i_block_d0 in nl.affine_range(16):"

"""Expected ISA call with 6D slicing."""
KERNEL_ISA_CALL_1 = (
    "nisa.nc_matmul("
    "dst=psum_output[0:128, 0, 0, 0, 0, 0:512], "
    "stationary=sbuf_a[0:128, 0, 0, 0, 0, 0:128], "
    "moving=sbuf_b[0:128, 0, 0, 0, 0, 0:512])"
)

"""Expected tensor_copy from PSUM to SBUF."""
KERNEL_TENSOR_COPY_1 = (
    "nisa.tensor_copy("
    "dst=sbuf_output[0:128, i_block_d1, i_block_d3, 0, 0, 0:512], "
    "src=psum_output[0:128, 0, 0, 0, 0, 0:512])"
)

"""Expected DMA store to HBM output."""
KERNEL_DMA_STORE_1 = (
    "nisa.dma_copy("
    "dst=output[i_block_d1*128:i_block_d1*128+128, "
    "i_block_d3*512:i_block_d3*512+512], "
    "src=sbuf_output[0:128, i_block_d1, i_block_d3, 0, 0, 0:512])"
)

"""Expected DMA load for stationary operand."""
KERNEL_DMA_LOAD_A_1 = (
    "nisa.dma_copy("
    "dst=sbuf_a[0:128, 0, 0, 0, 0, 0:128], "
    "src=a[i_block_d0*128:i_block_d0*128+128, "
    "i_block_d1*128:i_block_d1*128+128])"
)

"""Expected DMA load for moving operand."""
KERNEL_DMA_LOAD_B_1 = (
    "nisa.dma_copy("
    "dst=sbuf_b[0:128, 0, 0, 0, 0, 0:512], "
    "src=b[i_block_d0*128:i_block_d0*128+128, "
    "i_block_d3*512:i_block_d3*512+512])"
)
